<template>
	<o-layout
		:class="$s.Sheet"
		v-on="$listeners"
	>
		<o-layout-header
			:class="$s.Header"
			raised
			sticky
		>
			<!-- div needed to reduce the area of the icon focus state border -->
			<div :class="$s.HeaderClose">
				<o-button
					:class="$s.CloseIcon"
					@click="close(false)"
				>
					<o-icon name="x" />
				</o-button>
			</div>
			<div :class="$s.HeaderTitle">
				<h1
					v-if="!$slots.title && title"
					:class="$s.Title"
				>
					{{ title }}
				</h1>
				<div
					v-if="$slots.title"
					:class="$s.TitleSlot"
				>
					<slot name="title" />
				</div>
				<div
					v-if="$slots.steps"
					:class="$s.Steps"
				>
					<slot name="steps" />
				</div>
			</div>
			<sheet-actions @close="close" />
		</o-layout-header>

		<o-layout-content
			:class="[
				$s.Content,
				{
					[$s.backdrop]: backdrop,
					[$s.flush]: flush,
				},
			]"
		>
			<div
				:class="[
					$s.ContentInner,
					{ [$s.flush]: flush },
				]"
			>
				<slot />
			</div>
		</o-layout-content>
	</o-layout>
</template>

<script>
import { OLayer } from '@square/orbit/components/Layer';
import { OLayout, OLayoutHeader, OLayoutContent } from '@square/orbit/components/Layout';
import { OButton } from '@square/orbit/components/Button';
import { OIcon } from '@square/orbit/components/Icon';
import Spacer from '@square/orbit/utils/Spacer.vue';
import { showWarning } from '@square/orbit/utils/debug';

// @vue/component
const SheetActions = {
	functional: true,

	render(h, ctx) {
		const slots = ctx.slots();
		let { actions: actionsSlot = slots.default } = ctx.parent.$slots;

		if (typeof ctx.parent.$scopedSlots.actions === 'function') {
			actionsSlot = ctx.parent.$scopedSlots.actions;
			actionsSlot = actionsSlot(ctx.listeners);
		}

		return (
			<div class={[ctx.parent.$s.HeaderActions]}>
				<Spacer>
					{actionsSlot}
				</Spacer>
			</div>
		);
	},
};


export default {
	name: 'OSheet',

	components: {
		SheetActions,
		OLayout,
		OLayoutHeader,
		OLayoutContent,
		OButton,
		OIcon,
	},

	props: {
		beforeClose: {
			type: Function,
			default: undefined,
		},
		title: {
			type: String,
			default: undefined,
		},
		backdrop: {
			type: Boolean,
			default: false,
		},
		flush: {
			type: Boolean,
			default: false,
		},
	},

	inject: {
		layer: OLayer.key,
	},

	watch: {
		beforeClose(fn) {
			this.layer.configure({ beforeClose: fn });
		},
	},

	created() {
		this.layer.configure({
			cancelable: true,
			background: 'transparent',
			beforeClose: this.beforeClose,
			afterClose: exitVal => this.$emit('close', exitVal),
		});

		if (this.title && this.$slots.title) {
			showWarning('Sheet', 'The title prop won\'t render if the title slot is being used. Use <o-heading size="title-1">{{title}}</o-heading> in your title slot template to mimic the markup generated by the title prop.');
		}
	},

	methods: {
		close(exitVal) {
			return this.layer.close(exitVal)
				// can get rejected by user's before-close hook
				.catch(() => { /* no-op */ });
		},
	},
};
</script>

<style module="$s">
@import "@square/orbit/styles/vars.css";

:root {
	--sheet-bg-color: var(--color-white);
	--sheet-padding-vertical: var(--space-x4);
	--sheet-padding-horizontal: var(--space-x8);
	--sheet-mobile-padding-vertical: var(--space-x3);
	--sheet-mobile-padding-horizontal: var(--space-x4);
}

.Sheet {
	overflow-y: auto;
	height: 100vh;
	background-color: var(--sheet-bg-color);
	animation: slide-in 0.27s ease-in-out;
}

.HeaderClose,
.HeaderActions {
	flex: 0 1 20%;
	align-self: flex-start;
}

.CloseIcon {
	margin-left: calc(var(--space-x2) * -1);
}

.HeaderTitle {
	flex: 0 0 60%;
	padding: 0 var(--space);
	text-align: center;
}

.Title {
	composes: title-1 from "@square/orbit/styles/headings.css";
	margin: var(--space-half) 0;
	overflow: hidden;
}

.TitleSlot + .Steps,
.Title + .Steps {
	margin-top: var(--space-x2);
}

.HeaderActions {
	text-align: right;
	white-space: nowrap;
}

/* .Sheet needed to win specificity battle with .adjacent-to-header from LayoutContent */
.Sheet .Content {
	padding:
		var(--sheet-mobile-padding-vertical) var(--sheet-mobile-padding-horizontal)
		0 var(--sheet-mobile-padding-horizontal);

	&::after {
		height: var(--sheet-mobile-padding-vertical);
	}

	&.backdrop {
		background-color: var(--color-gray-10);
	}

	&.flush {
		padding: 0;
	}

	@media (--for-tablet-portrait-up) {
		padding:
			var(--sheet-padding-vertical) var(--sheet-padding-horizontal)
			0 var(--sheet-padding-horizontal);

		&::after {
			height: var(--sheet-padding-vertical);
		}
	}
}

.ContentInner:not(.flush) {
	max-width: 1200px;
	margin: 0 auto;
}

@keyframes slide-in {
	from {
		transform: translateY(200px);
	}

	to {
		transform: translateY(0);
	}
}
</style>
